version: '2'

run:
  timeout: 3m  # Linter timeout, increase for large projects

linters:
  default: none
  exclusions:
    paths:
      - vendor
      - generated
      - mocks
      - ".*\\.pb\\.go$"
      - ".*\\.gen\\.go$"
    rules:
      - path: '(.+)_test\.go'
        linters:
          - goconst
  enable:
    - govet          # Reports potential bugs
    - staticcheck    # Advanced checks for bugs and performance issues
    - errcheck       # Ensures all errors are checked
    - ineffassign    # Detects unused variable assignments
    - unused         # Finds unused code like functions or variables
    - gocyclo        # Detect cyclomatic complexity
    - goconst        # Detect repeated values that can be made constants
    - unconvert      # Detects unnecessary conversions
    - usestdlibvars  # Detects when standard library variables are used
    - bodyclose      # Check whether HTTP response bodies are closed
    - dupl           # Detects duplicate code
    - revive         # A faster, stricter, configurable, extensible, and beautiful linter for Go
  
  settings:
    revive:
      rules:
        - name: unexported-return
          disabled: true
